name: xsph
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - nvidia
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2024.8.30=py38h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.39=h59263cc_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py38h06a4308_0
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.4=py38h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.15.0.42=0
  - libcurand=10.4.0.35=h50d9014_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=1.1.1w=h7f8727e_0
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - pytorch=2.4.1=py3.8_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py38h5eee18b_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.3=py38h06a4308_0
  - setuptools=75.1.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.50.2=hb25bd0a_1
  - sympy=1.13.3=py38h06a4308_0
  - tk=8.6.14=h993c535_1
  - torchtriton=3.0.0=py38
  - torchvision=0.20.0=py38_cu121
  - typing_extensions=4.11.0=py38h06a4308_0
  - urllib3=2.2.3=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.1
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.1
      - backcall==0.2.0
      - cachetools==5.5.2
      - catkin-pkg==1.1.0
      - chardet==5.2.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.2.1
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docutils==0.20.1
      - einops==0.8.1
      - etils==1.3.0
      - executing==2.2.1
      - flatbuffers==25.9.23
      - fonttools==4.57.0
      - freetype-py==2.5.1
      - fsspec==2025.3.0
      - getkey==0.6.5
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - gym==0.23.1
      - gym-notices==0.1.0
      - h5py==3.11.0
      - h5py-cache==1.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipython==8.12.3
      - jedi==0.19.2
      - kiwisolver==1.4.7
      - lxml==6.0.0
      - markdown==3.7
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mujoco==3.2.3
      - mujoco-python-viewer==0.1.4
      - networkx==2.2
      - ninja==1.11.1.4
      - numpy==1.23.2
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - onnx==1.17.0
      - onnxruntime==1.19.2
      - opencv-python==4.12.0.88
      - packaging==25.0
      - parso==0.8.5
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - promise==2.3
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycollada==0.6
      - pygame==2.1.0
      - pyglet==2.1.6
      - pygments==2.19.2
      - pyopengl==3.1.0
      - pyopengl-accelerate==3.1.10
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - pysdf==0.1.9
      - python-dateutil==2.9.0.post0
      - pyvirtualdisplay==3.0
      - requests-oauthlib==2.0.0
      - rl-games==1.6.1
      - rospkg==1.6.0
      - rsa==4.9.1
      - scipy==1.10.1
      - sentry-sdk==2.34.1
      - setproctitle==1.3.6
      - shortuuid==1.0.13
      - smmap==5.0.2
      - stack-data==0.6.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==3.23.5
      - urdfpy==0.0.22
      - wandb==0.12.21
      - warp-lang==0.10.1
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - zipp==3.20.2
prefix: /home/asuka/miniconda3/envs/xsph
